### ISSUE TITLE
"releases list" fails with undefined function

### ISSUE THREAD

**Issue by SSUPII** [Realitaetsverlust/Carbuncle#1]
PHP 8.1.2 (cli)

`php carbuncle.php releases list` fails with call to undefined function.

```
PHP Fatal error:  Uncaught Error: Call to undefined function Realitaetsverlust\Carbuncle\curl_init() in /home/sergio/Carbuncle/Classes/Api.class.php:75
Stack trace:
#0 /home/sergio/Carbuncle/Classes/Api.class.php(41): Realitaetsverlust\Carbuncle\Api::fetchDataFromApi()
#1 /home/sergio/Carbuncle/Commands/ReleasesManager.php(14): Realitaetsverlust\Carbuncle\Api::fetchData()
#2 /home/sergio/Carbuncle/Carbuncle.php(46): Realitaetsverlust\Carbuncle\ReleasesManager->exec()
#3 /home/sergio/Carbuncle/Carbuncle.php(12): Realitaetsverlust\Carbuncle\Carbuncle->parseCommand()
#4 /home/sergio/Carbuncle/carbuncle.php(23): Realitaetsverlust\Carbuncle\Carbuncle->__construct()
#5 {main}
  thrown in /home/sergio/Carbuncle/Classes/Api.class.php on line 75

Fatal error: Uncaught Error: Call to undefined function Realitaetsverlust\Carbuncle\curl_init() in /home/sergio/Carbuncle/Classes/Api.class.php:75
Stack trace:
#0 /home/sergio/Carbuncle/Classes/Api.class.php(41): Realitaetsverlust\Carbuncle\Api::fetchDataFromApi()
#1 /home/sergio/Carbuncle/Commands/ReleasesManager.php(14): Realitaetsverlust\Carbuncle\Api::fetchData()
#2 /home/sergio/Carbuncle/Carbuncle.php(46): Realitaetsverlust\Carbuncle\ReleasesManager->exec()
#3 /home/sergio/Carbuncle/Carbuncle.php(12): Realitaetsverlust\Carbuncle\Carbuncle->parseCommand()
#4 /home/sergio/Carbuncle/carbuncle.php(23): Realitaetsverlust\Carbuncle\Carbuncle->__construct()
#5 {main}
  thrown in /home/sergio/Carbuncle/Classes/Api.class.php on line 75
  ```

**Comment by Realitaetsverlust** [comment]
Hi @SSUPII 

to me, this looks like the cURL-module is missing in your PHP-installation. Could you please execute `php -m | grep "curl"` and check if there is any output? 

I honestly assumed that the cURL-Extension is distributed by default on almost every distro, but I have updated the README to include all necessary modules.

**Comment by SSUPII** [comment]
> Hi @SSUPII
> 
> to me, this looks like the cURL-module is missing in your PHP-installation. Could you please execute `php -m | grep "curl"` and check if there is any output?
> 
> I honestly assumed that the cURL-Extension is distributed by default on almost every distro, but I have updated the README to include all necessary modules.

Not in Debian at least. In fact, `php -m | grep "curl"` has no output.

Simply installing `php-curl` from apt seems to have resolved the undefined function call. Anyway, thanks for pointing it out ^^

**Comment by Realitaetsverlust** [comment]
Quite interesting, I'm always fascinated how basic modules are missing in certain distros. But as mentioned, I added it to the README to avoid any confusion in the future.

Glad I could help, and please, if you have any suggestions or bugs, feel free to report them. :)
